---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template to create a data lake using AWS Glue and S3
Parameters:
  Environment:
    Description: Parameter for environment prefix, default value dev
    Type: String
    Default: dev
  Source:
    Description: Name of the Data Source
    Type: String
    Default: guru
  BucketName:
    Description: Name of the Bucket
    Type: String
    Default: freelance-analytics-codebase
  # GlueWorkflowRoleParameter:
  #   Description: Name of Glue Role
  #   Type: String
    
###########################################################################
 # AWS Resources
###########################################################################

Resources:
  GlueWorkFlowRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Allow Glue to call AWS services on your behalf.
      RoleName: 
        Fn::Join:
        - "-"
        - - Ref: Environment
          - freelance-analytics-glue-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: glue-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            - s3:ListBucket
            Resource: "*"
          - Effect: Allow
            Action:
            - iam:PassRole
            - iam:GetRole
            Resource:
            - arn:aws:iam::*:role/AWSGlueServiceRole*
            - Fn::Join:
              - ''
              - - 'arn:aws:iam::'
                - Ref: AWS::AccountId
                - ":role/freelance-analytics-glue-role-dev"
            Condition:
              StringLike:
                iam:PassedToService:
                - glue.amazonaws.com
          - Effect: Allow
            Action:
            - quicksight:PassDataSet
            - quicksight:CreateIngestion
            - quicksight:GetDashboardEmbedUrl
            - quicksight:ListUserGroups
            - quicksight:DescribeUser
            - quicksight:GetAuthCode
            - quicksight:ListTemplates
            - quicksight:DescribeDashboard
            - quicksight:ListGroups
            - quicksight:DescribeAnalysisPermissions
            - quicksight:ListThemeAliases
            - quicksight:ListIAMPolicyAssignmentsForUser
            - quicksight:DescribeDashboardPermissions
            - quicksight:DescribeAccountCustomization
            - quicksight:PassDataSource
            - quicksight:ListTagsForResource
            - quicksight:ListDataSets
            - quicksight:ListUsers
            - quicksight:ListTemplateAliases
            - quicksight:ListIngestions
            - quicksight:GetAnonymousUserEmbedUrl
            - quicksight:ListAnalyses
            - quicksight:GetSessionEmbedUrl
            - quicksight:DescribeIngestion
            - quicksight:ListIAMPolicyAssignments
            - quicksight:DescribeGroup
            - quicksight:DescribeAnalysis
            - quicksight:GetGroupMapping
            - quicksight:DescribeTheme
            - quicksight:ListThemes
            - quicksight:DescribeThemePermissions
            - quicksight:DescribeTemplatePermissions
            - quicksight:DescribeNamespace
            - quicksight:ListThemeVersions
            - quicksight:DescribeThemeAlias
            - quicksight:SearchDashboards
            - quicksight:DescribeIAMPolicyAssignment
            - quicksight:ListDataSources
            - quicksight:DescribeAccountSettings
            - quicksight:DescribeDataSource
            - quicksight:ListTemplateVersions
            - quicksight:DescribeTemplate
            - quicksight:ListGroupMemberships
            - quicksight:ListDashboards
            - quicksight:DescribeTemplateAlias
            - quicksight:SearchDirectoryGroups
            - quicksight:SearchAnalyses
            - quicksight:ListDashboardVersions
            - quicksight:DescribeDataSet
            - quicksight:ListNamespaces
            Resource: "*"
          - Effect: Allow
            Action:
            - iam:PassRole
            - iam:GetRole
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:iam::'
                - Ref: AWS::AccountId
                - ":role/freelance-analytics-glue-role-dev"
            Condition:
              StringEquals:
                iam:PassedToService: forecast.amazonaws.com
      ManagedPolicyArns:
  #    - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
      - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
  #    - arn:aws:iam::aws:policy/AmazonSESFullAccess

###########################################################################
 # AWS Glue Jobs
###########################################################################

  GuruDataIngest:
    Type: AWS::Glue::Job
    Properties: 
      Command:
        Name: pythonshell
        PythonVersion: '3'
        ScriptLocation: !Sub s3://${BucketName}/${Environment}/guru_handler.py
      DefaultArguments:
        "--incremental": "True"
        "--workflow_name": !Sub ${Environment}-${Source}-workflow
        "--extra-py-files": !Sub s3://${BucketName}/${Environment}/fa_guru_ingest.py,s3://${BucketName}/${Environment}/s3_utils.py
      ExecutionProperty: 
        MaxConcurrentRuns: 1
      GlueVersion : '1.0'
      MaxRetries: 0
      Name: !Sub ${Environment}-${Source}-jobs-data-ingest
      Role: !Ref GlueWorkFlowRole
        # Fn::ImportValue:
        #   !Sub ${GlueWorkflowRoleParameter}-Role
      Timeout: 2880

  GuruDataCurated:
    Type: AWS::Glue::Job
    Properties: 
      Command:
        Name: glueetl
        ScriptLocation: !Sub s3://${BucketName}/${Environment}/fa_guru_transformation.py
      ExecutionProperty: 
        MaxConcurrentRuns: 1
      GlueVersion : '2.0'
      WorkerType: "G.1X" 
      NumberOfWorkers: 2
      MaxRetries: 0
      Name: !Sub ${Environment}-${Source}-jobs-data-curated
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-disable"
      Role: !Ref GlueWorkFlowRole
        # Fn::ImportValue:
        #   !Sub ${GlueWorkflowRoleParameter}-Role
      Timeout: 2880

###########################################################################
 # AWS Glue Workflows
###########################################################################   

  GuruWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: Fetching raw data from the guru.com platform and storing it in an s3 bucket after transformation
      Name: !Sub ${Environment}-${Source}-workflow

###########################################################################
 # AWS Glue Triggers
###########################################################################      

  GuruIngestTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Description: To run guru raw data ingestion job
      Type: SCHEDULED
      Schedule: cron(0 12 * * ? *)
      WorkflowName: !Ref GuruWorkflow
      StartOnCreation: 'true'
      Actions:
        - JobName: !Sub ${Environment}-${Source}-jobs-data-ingest
      Name: !Sub ${Environment}-${Source}-jobs-Ingest-trigger

  GuruTransformationTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: CONDITIONAL
      WorkflowName: !Ref GuruWorkflow
      StartOnCreation: 'true'
      Actions:
        - JobName: !Sub ${Environment}-${Source}-jobs-data-curated
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            JobName: !Sub ${Environment}-${Source}-jobs-data-ingest
            State: SUCCEEDED
        Logical: ANY
      Name: !Sub ${Environment}-${Source}-jobs-transformation-trigger